In [1]:
import numpy as np

In [2]:
array = np.array([[1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]])

In [30]:
array.shape

(5, 3)

In [5]:
seg_col = array[:,1]
seg_col

array([ 6,  7,  8,  9, 10])

In [13]:
array2 = np.arange(15,56)
array2

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

In [14]:
array2[4] = 23
array2

array([15, 16, 17, 18, 23, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

In [15]:
array2[::-1]

array([55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39,
       38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22,
       21, 20, 23, 18, 17, 16, 15])

In [26]:

def devuelveArreglo(arr):
    lista = []
    for i in arr :
        if i % 2 == 0 :
            lista.append(i)
    return lista

lista_par = devuelveArreglo(array2)

lista_diagonal = np.diag(lista_par[:5])
lista_diagonal

array([[16,  0,  0,  0,  0],
       [ 0, 18,  0,  0,  0],
       [ 0,  0, 20,  0,  0],
       [ 0,  0,  0, 22,  0],
       [ 0,  0,  0,  0, 24]])

In [35]:
matriz = np.random.random((5,3))

In [29]:
lista_diagonal.ndim

2

In [36]:
matriz.T.shape

(3, 5)

In [37]:
matriz.T @ lista_diagonal

array([[ 4.14725115,  1.3362828 , 13.74410153,  1.633201  , 16.77103047],
       [ 4.64097925,  1.23401939,  1.07552683, 12.99335554,  6.69876551],
       [ 4.76772305, 11.71917477, 15.98064867,  0.33347586, 16.42309052]])