In [17]:
import sys

In [1]:
import numpy as np

In [2]:
array_1d = np.array([4.5, 3, 4])
type(array_1d)

numpy.ndarray

In [3]:
array_1d.ndim

1

In [4]:
array_1d.shape

(3,)

In [5]:
matriz = np.array([
    [1,2,3],
    [4,5,6]])
matriz

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
matriz.ndim

2

In [7]:
matriz.shape

(2, 3)

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((2))

array([1., 1.])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.random.random((2,3))

array([[0.3736787 , 0.9575453 , 0.0593319 ],
       [0.82482509, 0.25459568, 0.4310941 ]])

In [13]:
!cat text_file.txt

1,2,3
4,5,6
7,8,9


In [15]:
np_text = np.genfromtxt('text_file.txt', delimiter=',')
np_text

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [16]:
lista_2d = [[1,2,3], [4,5,6]]
lista_np_2d = np.array([[1,2,3], [4,5,6]])

In [18]:
sys.getsizeof(lista_2d)

88

In [19]:
sys.getsizeof(lista_np_2d)

160

In [20]:
big_lista = list(range(10000000))
big_lista_np = np.array(range(10000000))

In [21]:
sys.getsizeof(big_lista)

90000120

In [22]:
sys.getsizeof(big_lista_np)

80000096

In [23]:
%%timeit
sum(range(10000000))

221 ms ± 18 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [25]:
%%timeit
np.sum(np.arange(10000000))

49.1 ms ± 287 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [27]:
np.array([1.0, 4.3]).dtype

dtype('float64')

In [28]:
np.array([1.0, 4.3, 'patata']).dtype

dtype('<U32')

In [29]:
matriz_34 = np.array([
    [1,2,3,4],[5,6,7,8],[9,10,11,12]
])

In [30]:
matriz_34

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
matriz_34[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [33]:
matriz_34[:,1]

array([ 2,  6, 10])

In [34]:
seccion = matriz_34[:2]

In [35]:
seccion

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [36]:
seccion[0,0] = 100

In [37]:
matriz_34

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [39]:
matriz_32 = np.array([
    [1,4], [2,4], [5,0]
])

matriz_32

array([[1, 4],
       [2, 4],
       [5, 0]])

In [40]:
indice_filtrado = matriz_32 > 2
indice_filtrado

array([[False,  True],
       [False,  True],
       [ True, False]])

In [41]:
matriz_32[indice_filtrado]

array([4, 4, 5])